controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

salle_tp:
  resource: routes/salle/routes.yaml
  prefix: /salle

salle_tp_test_chap3et4:
  resource: routes/essai/routingTestChap3et4.yaml
  prefix: /essai
